{"name": "Prueba de login fallido", "status": "passed", "description": "Verifica que el login falle con credenciales incorrectas", "attachments": [{"name": "stdout", "source": "1913acd2-a19b-44d9-b932-7239bdacf59a-attachment.txt", "type": "text/plain"}], "start": 1747770539830, "stop": 1747770539940, "uuid": "639b5d7e-161f-43a0-84f2-df31adf01152", "historyId": "de6a588200aef5843b4845dc80b9c0dc", "testCaseId": "de6a588200aef5843b4845dc80b9c0dc", "fullName": "tests.test_eco_guardian.AuthTests#test_login_fallido", "labels": [{"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_eco_guardian"}, {"name": "subSuite", "value": "AuthTests"}, {"name": "host", "value": "EdwinFigueroa10"}, {"name": "thread", "value": "26600-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_eco_guardian"}]}