{"name": "Prueba de login fallido", "status": "passed", "description": "Verifica que el login falle con credenciales incorrectas", "attachments": [{"name": "stdout", "source": "25df0127-fdf6-46ed-80d6-6e1fdbbf4ccc-attachment.txt", "type": "text/plain"}], "start": 1747770654193, "stop": 1747770654454, "uuid": "ef3fd119-87d7-4a07-8da7-7d979601e292", "historyId": "de6a588200aef5843b4845dc80b9c0dc", "testCaseId": "de6a588200aef5843b4845dc80b9c0dc", "fullName": "tests.test_eco_guardian.AuthTests#test_login_fallido", "labels": [{"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_eco_guardian"}, {"name": "subSuite", "value": "AuthTests"}, {"name": "host", "value": "EdwinFigueroa10"}, {"name": "thread", "value": "41560-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_eco_guardian"}]}